### ISSUE TITLE
While showing the repositories in the 'All Repositories' Tab, please show the description.

### ISSUE THREAD

**Issue by rishiraj824** [rahulakrishna/gdginfo#8]

**Comment by rahulakrishna** [comment]
Right now the backend is fetching the repo name along with the top contributor of that repo. I'll see if I can get the description using the node backend for the react-app (In the next 30 minutes). Or else it should be an easy to include it in the backend.

**Comment by rishiraj824** [comment]
@rahulkrishna what's the status on this issue?

**Comment by rahulakrishna** [comment]
I tried to implement it on the js backend itself and got stuck at a point where I had to implement a chain of Promises. Balaji did it and we have the data. I just forgot to implement it in the frontend. Will do it asap.
